[project]
name = "comp558-inpainting"
version = "0.1.0"
description = "COMP558 final project on image inpainting"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.1.3",
    "python-dotenv>=1.0.1",
]
